### ISSUE TITLE
Undefined offset: 4

### ISSUE THREAD

**Issue by alejosv** [borodulin/yii2-momentjs#2]
Error in the file `/vendor/conquer/momentjs/MomentjsAsset.php` line 29:

    public static $language;
 
    public function registerAssetFiles($view)
    {
        if (self::$language !== false) {
            $language = self::$language ? self::$language : \Yii::$app->language;
            $this->js = ['moment-with-locales.min.js'];
            //assing locale globally
            $key = md5($js = "moment.locale('$language');");
    line 29 -->  $view->js[$view::POS_READY] = [$key => $js] + (array)$view->js[$view::POS_READY];
        } else {
            $this->js = ['moment.min.js'];
        }
        parent::registerAssetFiles($view);
    }

```

**Comment by borodulin** [comment]
Preferred way - make pull request
